language: php

php:
  - '8.1.0'

services:
  - mysql

env:
  global:
    - DB_HOST=127.0.0.1
    - DB_NAME=db_api
    - DB_USER=root-api
    - DB_PASS=root-api
    - DB_PORT=3306
    - XDEBUG_MODE=coverage

before_install:
  - mysql -e 'CREATE DATABASE db_api'

before_script:
  - composer require php-coveralls/php-coveralls:^2.2.0
  - composer install -n
  - cp .env.example .env

script:
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml
  - vendor/bin/php-coveralls --coverage_clover=clover.xml -v
